#!/bin/bash
# CortexOS Environment Variables
# Generated: 2025-06-09T14:01:53.871547

export CORTEXOS_ROOT="C:\Users\Blame\CortexOS"
export DATA_DIR="C:\Users\Blame\CortexOS\data"
export LOGS_DIR="C:\Users\Blame\CortexOS\logs"
export CONFIG_DIR="C:\Users\Blame\CortexOS\config"
export TEMP_DIR="C:\Users\Blame\CortexOS\temp"
export CACHE_DIR="C:\Users\Blame\CortexOS\cache"
export NVME_DEVICE_PATH="C:\Users\Blame\CortexOS"
export CUBE_STORAGE_PATH="C:\Users\Blame\CortexOS\storage\cube_storage"
export CONTRACT_STORAGE_PATH="C:\Users\Blame\CortexOS\storage\contracts"
export SECTOR_MAP_PATH="C:\Users\Blame\CortexOS\config\sector_map.json"
export STORAGE_INDEX_PATH="C:\Users\Blame\CortexOS\config\storage_index.db"
export NEURAL_DATA_DIR="C:\Users\Blame\CortexOS\neural_data"
export MEMORY_STORAGE_PATH="C:\Users\Blame\CortexOS\neural_data\memory.db"
export RESONANCE_DATA_PATH="C:\Users\Blame\CortexOS\neural_data\resonance.db"
export LEXICON_DATA_PATH="C:\Users\Blame\CortexOS\neural_data\lexicon.db"
export CONTEXT_DATA_PATH="C:\Users\Blame\CortexOS\neural_data\context.db"
export PATTERN_DATA_PATH="C:\Users\Blame\CortexOS\neural_data\patterns.db"
export INGESTION_QUEUE_PATH="C:\Users\Blame\CortexOS\temp\ingestion_queue"
export OUTPUT_QUEUE_PATH="C:\Users\Blame\CortexOS\temp\output_queue"
export PROCESSING_TEMP_PATH="C:\Users\Blame\CortexOS\temp\processing"
export STREAM_BUFFER_PATH="C:\Users\Blame\CortexOS\temp\stream_buffers"
export BATCH_STAGING_PATH="C:\Users\Blame\CortexOS\temp\batch_staging"
export BACKUP_DIR="C:\Users\Blame\CortexOS\backups"
export RECOVERY_DIR="C:\Users\Blame\CortexOS\recovery"
export CHECKPOINT_DIR="C:\Users\Blame\CortexOS\checkpoints"
export ARCHIVE_DIR="C:\Users\Blame\CortexOS\archives"
export PHASE1_DATA_DIR="C:\Users\Blame\CortexOS\neural_data\phase1"
export PHASE2_DATA_DIR="C:\Users\Blame\CortexOS\neural_data\phase2"
export PHASE3_DATA_DIR="C:\Users\Blame\CortexOS\neural_data\phase3"
export PHASE4_DATA_DIR="C:\Users\Blame\CortexOS\neural_data\phase4"
export PHASE5_DATA_DIR="C:\Users\Blame\CortexOS\neural_data\phase5"
export PHASE6_DATA_DIR="C:\Users\Blame\CortexOS\neural_data\phase6"
export METRICS_DIR="C:\Users\Blame\CortexOS\metrics"
export ANALYTICS_DIR="C:\Users\Blame\CortexOS\analytics"
export REPORTS_DIR="C:\Users\Blame\CortexOS\reports"
export ALERTS_DIR="C:\Users\Blame\CortexOS\alerts"

echo 'CortexOS environment variables loaded'
